"""Write the article's human-auditable claim-to-evidence map; validate local links."""
from pathlib import Path
import csv
ROOT=Path(__file__).resolve().parents[1]

def main():
    rows=[]
    def add(cid,claim,where,evidence,method,status,limit):
        for p in evidence.split(';'):
            assert (ROOT/p).is_file(),(cid,p)
        rows.append(dict(claim_id=cid,claim=claim,article_location=where,evidence=evidence,computation_or_check=method,status=status,qualification=limit))
    add('C01','50 primary worlds; 21 jointly valid worlds; 63 clustered targets','Abstract; 2.2; 3.1; S3','results/COHORT_ACCOUNTING.csv;results/SUMMARY.json','analyze.py + two independent raw readers','VERIFIED','Conditional population; targets are not independent experimental units')
    add('C02','17 ineligible, 11 split, 1 lost; no additional deep assay exclusion','3.1; S3.3','results/COHORT_ACCOUNTING.csv;reviews/statistics/STATISTICAL_SENSITIVITY.json','Count all 50 feasibility records','VERIFIED','Labels are operational tracker events, not proof of biological death/reproduction')
    add('C03','Each current target mass has at most 0.25 own-initial-mask labelled fraction at deep','Abstract; 2.2; 3.1; S3.2','results/WORLD_LEVEL_DATA.csv;reviews/complex_systems/SOURCE_CHECK.json','Raw deep_M and source tracer initialization','VERIFIED','Unmarked includes initially outside material; all targets retain positive own label')
    add('C04','Deep snapshots occur 709-927 steps after marking','3.1; Fig1','results/WORLD_LEVEL_DATA.csv','Min/max snapshot_time','VERIFIED','Not steps since world initialization; not a persistence half-life')
    add('C05','Target-memory erasure reduces tracked integrated uptake in every valid world','Abstract; 3.2; Fig2; S4','results/WORLD_LEVEL_DATA.csv;results/SUMMARY.json;reviews/statistics/FINAL_NUMERICAL_CHECK.json','Paired branch subtraction; average targets then worlds','VERIFIED_CONDITIONAL_CAUSAL_EFFECT','Effect of manipulated field in selected worlds, not identified mediation of assigned history')
    add('C06','Own effect exceeds sham and averaged other-target erasure effects','3.2; Fig2; S4','results/WORLD_LEVEL_DATA.csv;results/SUMMARY.json','Paired world contrasts and world t intervals','VERIFIED_CONDITIONAL','Designed directly coupled readout; model-world sampling assumption for intervals')
    add('C07','Fixed-within-branch control has a positive own effect','2.3; 3.2; S4','results/SUMMARY.json;source_model/experiments/individuation/nonmerging_confirm.py','Independent fixed-output contrasts; inspect mask timing','VERIFIED_WITH_SCOPE','Masks are chosen separately after intervention and settling; not identical across branches')
    add('C08','Uptake-channel ablation attenuates own effect but leaves a nonzero residual','3.2; Fig2; S4','results/SUMMARY.json;results/WORLD_LEVEL_DATA.csv','Frozen residual gate; paired half-own-minus-residual diagnostic','VERIFIED','Paired attenuation analysis post hoc; lambda-minus remains0.15')
    add('C09','Full readout ablation has exactly zero retained own-erasure contrast','S4','results/SUMMARY.json;reviews/editorial/EDITORIAL_SCALE_CHECK.json','Raw intact-full minus own-erased-full for each target','VERIFIED_DIAGNOSTIC','Expected by construction; not a test of active history maintenance')
    add('C10','Mean intact uptake3.0081; descriptive mean target/world relative reduction5.57%','3.2','results/WORLD_LEVEL_DATA.csv;results/SUMMARY.json;reviews/editorial/EDITORIAL_SCALE_CHECK.json','Average target ratios within world then across worlds','VERIFIED_DESCRIPTIVE','Distinct from ratio of means; absolute effect remains primary; no biological functional threshold')
    add('C11','L predicts assigned amplitude sum with frozen normalized skill0.3954','Abstract; 3.3','results/PREDICTIONS.csv;results/FOLD_LOSSES.csv;results/SUMMARY.json','World-excluded ridge; independent augmented least squares','VERIFIED_PREDICTIVE_ASSOCIATION','No identified causal history mediation; conditional representation/estimator result')
    add('C12','Frozen permutation diagnostic returns1/1001 with zero exceedances','3.3; S5.3','results/HISTORICAL_03M_REPLAY.json;reviews/statistics/STATISTICAL_SENSITIVITY.json','Two distinct implementations, 1000 within-world permutations','VERIFIED_ARITHMETIC','Conditional exchangeability not demonstrated; not exact randomized history causality')
    add('C13','Same seed stream is restarted for initialization and history amplitudes','2.2; S2.4; 4','source_model/experiments/individuation/turnover_engine_03g.py;source_model/edlab/experiments/exp_sc_00.py','Static source inspection','VERIFIED_LIMITATION','Quantitative impact unknown; not asserted to explain all observed decoding')
    add('C14','Local-exclusion conjunction fails; E/B descriptive bands include zero','3.3; Table1; Fig3','results/SUMMARY.json;results/HISTORICAL_03M_REPLAY.json','Frozen gate including positive lower L-skill band and four comparators','VERIFIED_PROCEDURAL_OUTCOME','Does not prove absence/equivalence or calibrated failure of generalization superiority')
    add('C15','Fold uncertainty has unestablished generalization coverage','2.4; Table1; S5.3','reviews/statistics/FINAL_MANUSCRIPT_REVIEW.md;reviews/editorial/INITIAL_EDITORIAL_REVIEW.md','Training overlap inspection; primary Bengio/Grandvalet reference','LIMITATION_DISCLOSED','Magnitude and direction of miscoverage not determined for this dataset')
    add('C16','E/Gm mask only target memory, retaining target body/other fields','2.4; S5.1','source_model/experiments/individuation/turnover_scope_features_03e.py;source_model/experiments/individuation/turnover_scope_features_03g.py','Static feature definitions; exact Gf L slice checks','VERIFIED','Not exclusively external access; finite/coarse features with unequal dimensions')
    add('C17','Refitted deletion sensitivity changes E/B/Gm gate passages','3.4; S6','reviews/statistics/STATISTICAL_SENSITIVITY.json','Delete one world then refit every remaining fold','VERIFIED_POST_HOC_DIAGNOSTIC','No new primary adjudication; jackknife coverage not established')
    add('C18','Growth copying and uniform removal preserve intensive memory algebraically','2.1; S2; 4','source_model/edlab/experiments/sc_mcm/engine.py;reviews/complex_systems/MODEL_SOURCE_NOTE.md','Direct algebra of extensive-field updates','ANALYTIC_REFERENCE','Only those substeps; full dynamics also transport/write/forget/smooth/clip')
    add('C19','Templating spatial term is exactly Laplacian/4; effective smoothing0.0125','2.1; S2.3','source_model/edlab/experiments/sc_iom/engine.py;reviews/complex_systems/SOURCE_CHECK.json','Static AST parameter extraction plus lattice identity','VERIFIED_ANALYTIC_REFERENCE','Not independent pattern restoration or identified error correction')
    add('C20','Exact model is mutual inhibition and split-step readout, with beta0.10','2.1; S2','source_model/edlab/experiments/sc_mcm/engine.py;reviews/complex_systems/SOURCE_CHECK.json;reviews/complex_systems/MODEL_SOURCE_NOTE.md','Static update equations and inherited config override','VERIFIED_MODEL_DESCRIPTION','No FitzHugh-Nagumo/active-reconstruction claim')
    add('C21','Seal/authorization precede recorded results; raw/manifests are hash verified','2.2; 3.4; S7.1','INPUT_MANIFEST.json;data/docs/individuation/TURNOVER_EXECUTION_MANIFEST_03G.json;DATA_PROVENANCE.md','Git ancestry audit and exact-byte input verification','VERIFIED_DOCUMENTARY_ORDER','Does not rule out unrecorded runs or prove another agent outcome-blind')
    add('C22','Reconstruction uses the same raw observations and runs no new worlds','2.5; 3.4; S8','scripts/reproduce.py;results/REPRODUCTION.json;DATA_PROVENANCE.md','Portable script imports and clean-copy negative test','VERIFIED_RECONSTRUCTION_SCOPE','Does not regenerate full spatial trajectories or independently validate physical constructs')
    add('C23','Other architectures/retrospective endpoints are not pooled into this sample','4; S7.2','INPUT_MANIFEST.json;reviews/complex_systems/INITIAL_REVIEW.md','All primary inputs belong to one sealed family','SCOPE_DECISION','CCRA/FDFLT/TBRT are documented separately, not extra independent worlds')
    add('C24','Local ownership absence, life, heredity and unique maintenance mechanisms are not established','Abstract; 3.3; 4','reviews/statistics/FINAL_MANUSCRIPT_REVIEW.md;reviews/complex_systems/FINAL_MANUSCRIPT_REVIEW.md;reviews/editorial/INITIAL_EDITORIAL_REVIEW.md','Construct review and explicit test limitations','NOT_ESTABLISHED','Unmet or unmeasured claims; not proof of impossibility')
    add('C25','Novelty is a worked computational assay case, not discovery that memory can survive turnover','1; 4','reviews/complex_systems/VERIFIED_REFERENCES.json;reviews/editorial/INITIAL_EDITORIAL_REVIEW.md','Targeted primary literature positioning','BOUNDED_EDITORIAL_JUDGMENT','Not exhaustive priority search, external peer review, or acceptance prediction')
    with (ROOT/'CLAIM_EVIDENCE_MATRIX.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator='\n');w.writeheader();w.writerows(rows)
    print('Claim matrix:',len(rows),'rows; all evidence files exist.')

if __name__=='__main__':main()
