"""OBDI01 §8 — operating characteristics of the LEGACY D GATE, recomputed and stored in
full so the artefact is self-contained. No new engine start: the resampling uses only the
frames already recorded in the OBTC02 raw archives.

Truth is H-bound BY CONSTRUCTION: every series below was generated by the frozen LawSpec,
so any FAIL of the gate on these series is a property of the gate, not of the physics.
"""
from __future__ import annotations

import json

import numpy as np

RAW = "/home/claude/OBDI01/verify/obtc02/wc/OBTC02/raw"
OUT = "/home/claude/OBDI01/out"
BURN_IN, ABS_BOUND, FRAC, REQ = 2000, 12.8, 0.35, 0.95
BLOCK = 10
DRAWS = 4000
HEALTHY = [("P__seed9102", 36), ("P__seed9103", 36), ("P__seed9104", 36),
           ("P__seed9105", 36), ("P__seed9106", 36),
           ("D__seed9501", 72), ("D__seed9502", 72), ("D__seed9503", 72)]


def series(tag):
    z = np.load(f"{RAW}/{tag}.npz", allow_pickle=True)
    fr = [json.loads(s) for s in z["frames"]]
    fr = [f for f in fr if f["step"] > BURN_IN]
    r80 = np.array([f["r80_organiser"] for f in fr], float)
    r80c = np.array([f.get("r80", np.nan) for f in fr], float)
    return r80, r80c, len(fr)


def lag1(x):
    x = x[np.isfinite(x)]
    if len(x) < 3 or x.std() == 0:
        return float("nan")
    return float(np.corrcoef(x[:-1], x[1:])[0, 1])


def block_bootstrap(rng, x, n_out, block):
    """Stationary block resampling: preserves short-range dependence, destroys nothing else."""
    n = len(x)
    nb = int(np.ceil(n_out / block))
    starts = rng.integers(0, n, size=nb)
    idx = (starts[:, None] + np.arange(block)[None, :]) % n
    return x[idx.ravel()[:n_out]]


def fail_rate_one_arm(rng, x, L, n_frames, block, draws=DRAWS):
    """The gate is applied to ONE arm, so the resampling unit is one arm's own series."""
    bound = min(ABS_BOUND, FRAC * L)
    out = np.empty(draws)
    for d in range(draws):
        s = block_bootstrap(rng, x, n_frames, block)
        out[d] = float(np.mean(s <= bound))
    return float(np.mean(out < REQ)), out


def fail_rate(rng, arms, L, n_frames, block, draws=DRAWS):
    """Operating characteristic of 'a healthy arm at this L': the per-arm failure rate,
    averaged over the arms actually observed at this L. Pooling the arms first would mix the
    between-seed variance into the marginal and is NOT what the gate does."""
    per, dists = {}, []
    for tag, x in arms:
        p, d = fail_rate_one_arm(rng, x, L, n_frames, block, draws)
        per[tag] = p
        dists.append(d)
    dist = np.concatenate(dists)
    return float(np.mean(list(per.values()))), dist, per


def main():
    rng = np.random.default_rng(20260811)
    per_arm_ac, pools = {}, {36: [], 72: []}
    obs_len, cloud = {}, {36: [], 72: []}
    for tag, L in HEALTHY:
        r80o, r80c, n = series(tag)
        r80o = r80o[np.isfinite(r80o)]
        per_arm_ac[tag] = lag1(r80o)
        pools[L].append((tag, r80o))
        cloud[L].append(r80c)
        obs_len[tag] = n

    res = {"note": ("block bootstrap, block length %d frames, over all healthy P and D arms "
                    "of OBTC02, passing or not; the truth is H-bound by construction since "
                    "the data come from the frozen LawSpec" % BLOCK),
           "draws": DRAWS, "block_length": BLOCK,
           "arms_used": [t for t, _ in HEALTHY],
           "lag1_autocorrelation": {"per_arm": per_arm_ac,
                                    "mean": float(np.nanmean(list(per_arm_ac.values()))),
                                    "min": float(np.nanmin(list(per_arm_ac.values()))),
                                    "max": float(np.nanmax(list(per_arm_ac.values())))},
           "by_L": {}, "frame_count_dependence": {}, "autocorrelation_destroyed": {}}

    n_ref = 180
    for L in (36, 72):
        arms = pools[L]
        p, dist, per = fail_rate(rng, arms, L, n_ref, BLOCK)
        res["by_L"][str(L)] = {
            "bound": min(ABS_BOUND, FRAC * L),
            "binding_term": "domain_fraction" if FRAC * L < ABS_BOUND else "absolute",
            "n_frames": n_ref, "n_arms": len(arms),
            "median_bootstrap_fraction": float(np.median(dist)),
            "q05_bootstrap_fraction": float(np.quantile(dist, 0.05)),
            "false_negative_rate": p, "false_negative_rate_per_arm": per}
        # dependence on the amount of data
        res["frame_count_dependence"][str(L)] = {
            str(n): fail_rate(rng, arms, L, n, BLOCK, draws=2000)[0]
            for n in (60, 180, 540, 1800)}
        # same marginal, dependence removed
        res["autocorrelation_destroyed"][str(L)] = fail_rate(rng, arms, L, n_ref, 1,
                                                             draws=2000)[0]

    res["bound_L36"] = res["by_L"]["36"]["bound"]
    res["bound_L72"] = res["by_L"]["72"]["bound"]
    res["bound_ratio"] = res["bound_L72"] / res["bound_L36"]
    med, medarm = {}, {}
    for L in (36, 72):
        c = np.concatenate(cloud[L])
        med[L] = float(np.nanmedian(c))
        medarm[L] = float(np.median([np.nanmedian(a) for a in cloud[L]]))
    res["median_r80_L36"], res["median_r80_L72"] = med[36], med[72]
    res["relative_difference"] = abs(med[72] - med[36]) / med[36]
    res["median_of_arm_medians"] = {"L36": medarm[36], "L72": medarm[72],
                                    "relative_difference": abs(medarm[72] - medarm[36])
                                    / medarm[36]}
    res["legacy_gate_OC"] = {"note": res["note"],
                             "L36_false_negative_rate": res["by_L"]["36"]["false_negative_rate"],
                             "L72_false_negative_rate": res["by_L"]["72"]["false_negative_rate"]}
    json.dump(res, open(f"{OUT}/_legacy_gate_OC.json", "w"), indent=1, default=str)
    print("lag1 autocorrelation  mean %.3f  range %.3f-%.3f"
          % (res["lag1_autocorrelation"]["mean"], res["lag1_autocorrelation"]["min"],
             res["lag1_autocorrelation"]["max"]))
    for L in (36, 72):
        b = res["by_L"][str(L)]
        print("L=%-3d bound %.2f (%s)  median frac %.4f  q05 %.4f  P(fail)=%.3f"
              % (L, b["bound"], b["binding_term"], b["median_bootstrap_fraction"],
                 b["q05_bootstrap_fraction"], b["false_negative_rate"]))
        print("      frames ->", res["frame_count_dependence"][str(L)],
              " ac-destroyed", round(res["autocorrelation_destroyed"][str(L)], 3))
    print("bound ratio %.4f   median r80 %.4f vs %.4f  rel diff %.4f"
          % (res["bound_ratio"], res["median_r80_L36"], res["median_r80_L72"],
             res["relative_difference"]))


if __name__ == "__main__":
    main()
