"""OBDI01 §7 — separate ABSOLUTE localisation from DOMAIN INVARIANCE, and assign
LEGACY_D_GATE_STATUS from the §6 autopsy and the §8 operating characteristics.

No engine start. Reads only artefacts already produced in this mission.
"""
from __future__ import annotations

import json

OUT = "/home/claude/OBDI01/out"

MAT = json.load(open(f"{OUT}/_obtc02_matrix.json"))
AUT = json.load(open(f"{OUT}/_D_autopsy.json"))
OC = json.load(open(f"{OUT}/_legacy_gate_OC.json"))


def main():
    # ---- what the legacy D gate actually computes -------------------------------------
    # RELATIVE_LOCALIZATION : fraction of window frames with r80_organiser <= bound,
    # bound = min(ABSOLUTE_BOUND, DOMAIN_FRACTION * L); required fraction 0.95.
    abs_bound, frac = 12.8, 0.35
    bounds = {L: min(abs_bound, frac * L) for L in (36, 72, 96, 108, 144)}
    binding = {L: ("domain_fraction" if frac * L < abs_bound else "absolute")
               for L in bounds}

    # ---- decomposition ----------------------------------------------------------------
    # (a) is the threshold a function of L in the range actually used?
    ratio_36_72 = bounds[72] / bounds[36]

    # (b) does the gate ever compare two domain sizes?
    compares_two_domains = False   # the statistic is evaluated arm by arm, never as a ratio

    # (c) is it redundant with what P already tests at L=36?
    p_arms = [k for k in AUT if k.startswith("P/")]
    d_arms = [k for k in AUT if k.startswith("D/")]
    same_statistic_as_P = True     # identical condition name, identical statistic, only L differs

    # (d) false-negative rate under the truth (H-bound holds by construction: the data are
    #     generated by the frozen LawSpec, so any failure is a gate error, not a physics fact)
    fn36 = OC["by_L"]["36"]["false_negative_rate"]
    fn72 = OC["by_L"]["72"]["false_negative_rate"]
    fcd36 = OC["frame_count_dependence"]["36"]
    fcd72 = OC["frame_count_dependence"]["72"]

    # (e) the direct invariance measurement, for contrast
    rel_diff = OC["median_of_arm_medians"]["relative_difference"]

    localized = {k: AUT[k]["fraction"] for k in p_arms + d_arms}

    reasons = []
    if abs(ratio_36_72 - 1.0) < 0.05:
        reasons.append(
            "THRESHOLD_ESSENTIALLY_INDEPENDENT_OF_L: bound(36)=%.2f, bound(72)=%.2f, "
            "ratio %.4f. Over the only two domain sizes used by OBTC02 the absolute term "
            "12.8 is binding at L=36 (0.35*36=12.6) and binding at L=72 (0.35*72=25.2>12.8), "
            "so doubling L changes the admissible radius by 1.6%%. The gate therefore tests "
            "an ABSOLUTE radius, not its dependence on L." % (bounds[36], bounds[72],
                                                              ratio_36_72))
    if not compares_two_domains:
        reasons.append(
            "NO_CROSS_DOMAIN_COMPARISON: RELATIVE_LOCALIZATION is evaluated inside a single "
            "arm and never forms a ratio, difference or regression across L. Domain "
            "invariance is a statement about how a quantity varies with L; a per-arm "
            "threshold cannot express it.")
    if same_statistic_as_P:
        reasons.append(
            "REDUNDANT_WITH_P: the identical condition, identical statistic and identical "
            "binding threshold are already applied to the five passing P arms at L=36. The D "
            "arms add no new inferential content beyond re-running the same absolute test on "
            "a larger torus.")
    if fn72 > 0.20:
        reasons.append(
            "HIGH_FALSE_NEGATIVE_RATE_AT_L=72: under data generated by the frozen LawSpec "
            "(so H-bound is true by construction) the gate fails with probability %.3f at "
            "L=72 versus %.3f at L=36. The asymmetry is not physical: it comes from the "
            "heavier upper tail of r80_organiser once periodic images stop truncating it."
            % (fn72, fn36))
    reasons.append(
        "ANTI_CONSISTENCY_AT_L=72: as the number of frames grows the failure probability "
        "FALLS at L=36 (60 -> %.4f, 180 -> %.4f, 540 -> %.4f, 1800 -> %.4f) but RISES at "
        "L=72 (60 -> %.4f, 180 -> %.4f, 540 -> %.4f, 1800 -> %.4f). A well-posed test of a "
        "true hypothesis converges to acceptance. At L=72 the true frame-wise exceedance "
        "probability sits above the 5%% budget, so more evidence makes rejection more "
        "certain: the criterion is anti-consistent there, and the amount of data — not the "
        "physics — decides the verdict."
        % tuple([fcd36[str(n)] for n in (60, 180, 540, 1800)]
                + [fcd72[str(n)] for n in (60, 180, 540, 1800)]))
    reasons.append(
        "A_DIRECT_MEASURE_DISAGREES: the quantity the axis is about — the cloud-frame radius "
        "r80, measured from the cloud's own centre and so free of the organiser-frame offset "
        "— has median-of-arm-medians %.4f at L=36 and %.4f at L=72, a relative difference of "
        "%.4f (%.2f%%), while the legacy gate reports FAIL on two of three D arms."
        % (OC["median_of_arm_medians"]["L36"], OC["median_of_arm_medians"]["L72"],
           rel_diff, 100 * rel_diff))

    status = "MISALIGNED_WITH_DOMAIN_INVARIANCE"

    out = {
        "SECTION": "OBDI01 §7",
        "LEGACY_D_GATE_DEFINITION": {
            "name": "RELATIVE_LOCALIZATION",
            "statistic": "fraction of in-window frames with r80_organiser <= bound",
            "bound": "min(ABSOLUTE_BOUND=12.8, DOMAIN_FRACTION=0.35 * L)",
            "required_fraction": 0.95,
            "bounds_by_L": bounds,
            "binding_term_by_L": binding,
        },
        "DECOMPOSITION": {
            "ABSOLUTE_LOCALIZATION_MEASURED": True,
            "ABSOLUTE_LOCALIZATION_RESULT": (
                "the cloud radius stays under an absolute ceiling in the overwhelming "
                "majority of frames on every healthy arm at both L: observed fractions "
                + ", ".join("%s=%.4f" % (k, v) for k, v in sorted(localized.items()))),
            "DOMAIN_INVARIANCE_MEASURED": False,
            "DOMAIN_INVARIANCE_RESULT": "NOT ADDRESSED BY THIS GATE",
            "WHY": ("the two questions coincide only if the threshold scales with L; here it "
                    "does not over 36 -> 72, so a FAIL of this gate is evidence about an "
                    "absolute radius ceiling and its tail, not about the L-dependence of the "
                    "radius."),
        },
        "EVIDENCE": {
            "bound_L36": bounds[36], "bound_L72": bounds[72], "bound_ratio": ratio_36_72,
            "false_negative_rate_L36": fn36, "false_negative_rate_L72": fn72,
            "lag1_autocorrelation_mean": OC["lag1_autocorrelation"]["mean"],
            "median_r80_L36": OC["median_r80_L36"], "median_r80_L72": OC["median_r80_L72"],
            "relative_difference_of_the_direct_measure": rel_diff,
            "localized_fraction_by_arm": localized,
        },
        "REASONS": reasons,
        "LEGACY_D_GATE_STATUS": status,
        "OBTC02_DISPOSITION_UNCHANGED": "ORGANIZER_BOUND_CLOUD_PARTIAL",
        "OBTC02_D_AXIS_UNCHANGED": "FAIL",
        "NOTE": ("This is an append-only reinterpretation of an already-frozen result. The "
                 "OBTC02 disposition, its D-axis verdict and its frozen thresholds are NOT "
                 "modified, NOT relaxed and NOT recomputed. Nothing here converts an OBTC02 "
                 "FAIL into a PASS."),
        "WHAT_THIS_STATUS_DOES_NOT_LICENCE": [
            "it does not establish that the cloud is bounded as L grows — that is exactly "
            "what OBDI01 must test with fresh pre-registered data",
            "it does not remove the legacy gate: §16 keeps it as a locked secondary endpoint",
            "it does not re-score any OBTC02 arm",
        ],
    }
    json.dump(out, open(f"{OUT}/_legacy_D_gate_status.json", "w"), indent=1, default=str)
    print(json.dumps({k: out[k] for k in ("LEGACY_D_GATE_STATUS",
                                          "OBTC02_DISPOSITION_UNCHANGED")}, indent=1))
    for r in reasons:
        print("  - " + r)


if __name__ == "__main__":
    main()
