#!/usr/bin/env python3
"""Renders PROVENANCE_LEDGER.md from PROVENANCE_LEDGER.csv. Counts are computed, never typed."""
import csv, json, os
D = os.path.dirname(os.path.abspath(__file__)) + "/.."
rows = list(csv.DictReader(open(os.path.join(D, "PROVENANCE_LEDGER.csv"), encoding="utf-8")))
counts = {s: sum(1 for r in rows if r["status"] == s) for s in ("VERIFIED", "NOT_FOUND", "DIFFERS")}
SEC = [("D", "A. Frozen prospective design (PRESEAL `9b7580bc`)"),
       ("E", "B. Engine / model definition"),
       ("R", "C. Results (RESULTS `830c2d0`, family 53001-53032 run once)"),
       ("A", "D. POST HOC addendum R* = 0.2575 (`9c8a62c`) - NOT part of the frozen design"),
       ("P", "E. Prior-lineage context (superseded / invalidated values, quoted only as contrast)"),
       ("SEAL", "F. Seal integrity: PRESEAL SHA-256 manifest re-hashed"),
       ("V", "G. Reproduction of the analysis stage (this deposit pass)"),
       ("X", "H. Re-derivation discrepancies (DIFFERS)"),
       ("N", "I. Identity, licence and identifiers - nothing invented")]
def bucket(rid):
    if rid.startswith("SEAL"): return "SEAL"
    return rid[0]
esc = lambda s: s.replace("|", "\\|").replace("\n", " ")
out = []
out.append("# Provenance ledger - LCI-CAUSAL-NONMERGING-CONFIRM-02\n")
out.append("*Publication document 3 of 4. Machine-readable twin: `PROVENANCE_LEDGER.csv`. "
           "Generated by `verification/build_ledger.py` (SHA-256 values are recomputed from the "
           "deposit copies at build time) and rendered by `verification/render_ledger.py`.*\n")
out.append("## Status vocabulary (binding)\n")
out.append("- **VERIFIED** - traced to an exact repository artefact: exact path, exact commit, exact SHA-256, "
           "exact JSON key / CSV filter-row / table cell. **This does NOT mean independently reproduced.**\n"
           "- **NOT_FOUND** - no exact source exists. The value is omitted from the manuscript or carried "
           "explicitly labelled as NOT_FOUND. It is never stated as a fact.\n"
           "- **DIFFERS** - an exact source exists and disagrees with the asserted value. Such values are "
           "**not** retained merely because a mission prompt asserted them. **A mission prompt is not "
           "scientific evidence.**\n")
out.append("## Counts\n")
out.append("| status | rows |\n|---|---|")
for s in ("VERIFIED", "NOT_FOUND", "DIFFERS"):
    out.append("| %s | %d |" % (s, counts[s]))
out.append("| **total** | **%d** |\n" % len(rows))
out.append("**Seal integrity: 8 of 8** SHA-256 entries in the PRESEAL `sealed_file_sha256` manifest match the "
           "committed content exactly - no post-seal code drift.\n")
out.append("**Only VERIFIED values appear as unqualified facts in `MANUSCRIPT.md` and "
           "`DEPOSIT_METADATA.json`.** The five DIFFERS rows are full-precision floating-point values that the "
           "manuscript deliberately does *not* quote at that precision; the nine NOT_FOUND rows are identity, "
           "licence and identifier fields that were left empty rather than invented.\n")
out.append("## Commit chain\n")
out.append("| commit | role | exists |\n|---|---|---|")
out.append("| `9b7580bc` (`9b7580bc3a09293a4b0b19b70cff8c39c5cb1378`) | PRESEAL - frozen prospective design | yes |")
out.append("| `830c2d0` (`830c2d006f5278295e965887f8ccedee34d47e67`) | RESULTS - family run once | yes |")
out.append("| `9c8a62c` (`9c8a62cd3f6794eb9ac435f638671e5561086cd0`) | ADDENDUM - R* post hoc sensitivity | yes |")
out.append("| `6470513` (`647051382f64512508fd0602603f3d001b505529`) | parent (merge-incident audit) | yes |\n")
out.append("Branch `exp/lci-causal-nonmerging-confirm-02`; nothing pushed, tagged, merged or published.\n")
for key, title in SEC:
    sel = [r for r in rows if bucket(r["id"]) == key]
    if not sel: continue
    out.append("## " + title + "\n")
    out.append("| id | symbol | value | source path | commit | source SHA-256 | locator | mode | status | note |")
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in sel:
        out.append("| %s | %s | `%s` | `%s` | `%s` | `%s` | `%s` | %s | **%s** | %s |" % (
            r["id"], esc(r["symbol"]), esc(r["value"]), r["source_path"], r["source_commit"],
            r["source_sha256"][:16] + ("..." if len(r["source_sha256"]) > 16 else ""),
            esc(r["locator"]), esc(r["verification_mode"]), r["status"], esc(r["note"])))
    out.append("")
out.append("*Full 64-hex SHA-256 values for every deposited file are in `SHA256SUMS`. "
           "Source SHA-256 columns above are truncated to 16 hex characters for readability only.*\n")
open(os.path.join(D, "PROVENANCE_LEDGER.md"), "w", encoding="utf-8").write("\n".join(out))
print("wrote PROVENANCE_LEDGER.md  rows=%d %s" % (len(rows), counts))
