"""FDOT01 §21 — terminal disposition, computed from committed inputs."""
from __future__ import annotations
import json, datetime, os
REPO="/home/claude/edl"; OUT=f"{REPO}/FDOT01/out"
def main():
    L=lambda f: json.load(open(f"{OUT}/{f}"))
    PR=L("FDOT01_PRIMARY_ANALYSIS.json"); SE=L("FDOT01_SECONDARY_ANALYSIS.json")
    RV=L("FDOT01_ADVERSARIAL_REVIEW.json"); AD=L("FDOT01_REVIEW_ADJUDICATION.json")
    RM=L("FDOT01_RAW_MANIFEST.json"); FX=L("FDOT01_FIXTURES.json")
    DU=L("FDOT01_DURABILITY.json"); DA=L("FDOT01_DETECTION_ASSURANCE.json")
    gates={
     "ALL_160_PRIMARY_WORLDS_ACCOUNTED":PR["ALL_PRIMARY_WORLDS_PRESENT"],
     "NO_TECHNICAL_FAILURE":PR["TECHNICAL_FAILURES"]==0,
     "ALL_RAN_FULL_HORIZON":PR["ALL_RAN_FULL_HORIZON"],
     "NO_OUTCOME_DRIVEN_REPLACEMENT":RM["RESERVES_USED"]==0,
     "FIXTURES_ALL_PASS":FX["ALL_PASS"],
     "TWO_IMPLEMENTATIONS_AGREE":FX["A_AND_B_AGREE_ON_EVERY_FIXTURE"],
     "NO_LOAD_BEARING_REVIEW_DEFECT":not AD["LOAD_BEARING_DEFECT_CONFIRMED_AFTER_ADJUDICATION"],
     "PRE_RUN_DURABILITY":DU["WINDOWS_PRE_RUN_DURABILITY"]=="PASS",
     "RAW_DURABILITY_BEFORE_ANALYSIS":DU["WINDOWS_RAW_DURABILITY_BEFORE_ANALYSIS"]=="PASS"}
    valid=all(gates.values())
    K=PR["PRIMARY_K"]
    disp=("FDOT01_TECHNICALLY_INVALID" if not valid else
          "FUNCTIONAL_ORGANISER_TURNOVER_PROSPECTIVELY_REPLICATED" if K>=PR["REPLICATION_THRESHOLD"] else
          "FUNCTIONAL_ORGANISER_TURNOVER_NOT_PROSPECTIVELY_REPLICATED")
    D={"PROGRAMME":"FDOT01 — FRESH-DAUGHTER-ORGANISER-TURNOVER-TEST-01",
     "GENERATED_UTC":datetime.datetime.now(datetime.timezone.utc).isoformat(),
     "PRIMARY_POINT":"B1","PRIMARY_N":PR["PRIMARY_N"],"PRIMARY_REPLICATION_THRESHOLD":PR["REPLICATION_THRESHOLD"],
     "PRIMARY_FUNCTIONAL_TURNOVER_COUNT":K,"PRIMARY_FUNCTIONAL_TURNOVER_RATE":PR["FRESH_RATE"],
     "PRIMARY_EXACT_95_CI":PR["EXACT_95_CI"],"PRIMARY_ONE_SIDED_LOWER_95":PR["ONE_SIDED_LOWER_95"],
     "COMPLETE_TURNOVER_COUNT":PR["K_COMPLETE_TURNOVER"],
     "COMPLETE_TURNOVER_RATE":PR["COMPLETE_RATE"],"COMPLETE_EXACT_95_CI":PR["COMPLETE_EXACT_95_CI"],
     "BIRTH_THEN_DEATH_INTERVALS":SE["birth_then_death_intervals"],
     "DEATH_THEN_BIRTH_INTERVALS":SE["death_then_birth_intervals"],
     "DECISION_GATES":gates,"TECHNICALLY_VALID":valid,
     "DETECTION_ASSURANCE_AT_THE_CONSERVATIVE_INPUT":DA["ASSURANCE"]["STRICT_RULE_one_sided_95_lower"],
     "K_LESS_THAN_2_IS_NOT_EVIDENCE_OF_ABSENCE":DA["CONSEQUENCE_FOR_INTERPRETATION"],
     "FINAL_DISPOSITION":disp,
     "CLAIM_CEILING":("a positive result establishes only that a spatial organising centre at the frozen "
       "B1 law retained its identity and its local X production through a complete constituent turnover, "
       "in more than one independent fresh world. It establishes nothing about a daughter's independence "
       "from a parent, nothing about a second generation, and nothing about heredity."),
     "MINIMAL_REPRODUCTION_STATUS":"NOT_ESTABLISHED","STRONG_SELF_REPRODUCTION_STATUS":"NOT_TESTED",
     "HEREDITY_STATUS":"NOT_TESTED","R3_STATUS":"NOT_TESTED","H3_STATUS":"NOT_TESTED",
     "REPRODUCTION_STATUS":"NOT_TESTED","AUTONOMOUS_COHESION_STATUS":"NOT_ESTABLISHED",
     "X_LAWSPEC_BASELINE":"UNCHANGED","ARCHITECTURE_CHANGE_NECESSITY":"NOT_ESTABLISHED",
     "NEXT_SCIENTIFIC_ELIGIBILITY":("HANDOFF_MINIMAL_REPRODUCTION_CAUSAL_INTEGRATION_01 (zero run)"
       if disp=="FUNCTIONAL_ORGANISER_TURNOVER_PROSPECTIVELY_REPLICATED"
       else "HANDOFF_ORGANISER_TURNOVER_FAILURE_AUTOPSY_01 (zero run)"),
     "NEW_SCIENTIFIC_WORLDS_USED":160}
    json.dump(D,open(f"{OUT}/FDOT01_FINAL_DISPOSITION.json","w"),indent=2)
    print(json.dumps({k:D[k] for k in ("PRIMARY_FUNCTIONAL_TURNOVER_COUNT","PRIMARY_FUNCTIONAL_TURNOVER_RATE",
      "COMPLETE_TURNOVER_COUNT","TECHNICALLY_VALID","FINAL_DISPOSITION")},indent=1))
    print("gates:",json.dumps(gates,indent=1))
if __name__=="__main__": main()
