#!/usr/bin/env python3
"""Emit every manuscript number as a LaTeX macro, straight from the reconciliation.

The manuscript may not contain a bare numeral for any reported quantity: it calls a
macro, the macro's value comes from a hashed source file, and code/paper_claim_lint.py
checks that every macro used exists and that no macro is defined twice.
"""
import json, os, re

PKG = "/home/claude/edl/paper/organiser-bound-source-response-operator"
REC = json.load(open(f"{PKG}/provenance/PAPER_NUMERICAL_RECONCILIATION.json", encoding="utf-8"))

def camel(label):
    parts = re.sub(r"[^0-9a-zA-Z]+", " ", label).split()
    out = parts[0].lower() + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return re.sub(r"[0-9]", lambda m: "zothfvsxen"[int(m.group())] if False else
                  ["Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine"][int(m.group())], out)

def fmt(v, rule):
    if isinstance(v, bool):
        return r"\textsc{true}" if v else r"\textsc{false}"
    if isinstance(v, int):
        return f"{v:d}"
    if isinstance(v, float):
        if rule.startswith("exact"):
            return f"{v:g}"
        if "decimal" in rule:
            n = int(re.search(r"(\d+)", rule).group(1))
            return f"{v:.{n}f}"
        n = int(re.search(r"(\d+)", rule).group(1)) if re.search(r"(\d+)", rule) else 6
        s = f"%.{n}g" % v
        if "e" in s or "E" in s:
            m, e = s.split("e")
            return f"{m}\\times 10^{{{int(e)}}}"
        return s
    s = str(v)
    if re.fullmatch(r"[0-9a-f]{32,}", s):          # a hash: allow a break every 8 characters
        return r"\allowbreak{}".join(s[i:i + 8] for i in range(0, len(s), 8))
    s = s.replace("_", r"\_\allowbreak{}").replace("%", r"\%").replace("&", r"\&")
    return s

LINES = [r"% GENERATED by code/emit_numbers.py from provenance/PAPER_NUMERICAL_RECONCILIATION.json.",
         r"% Do not edit. Every macro below is a value read from a hashed source file.",
         ""]
seen = {}
for r in REC["ROWS"]:
    name = camel(r["MANUSCRIPT_LABEL"])
    if name in seen:
        raise SystemExit(f"macro collision: {name} from {r['MANUSCRIPT_LABEL']} and {seen[name]}")
    seen[name] = r["MANUSCRIPT_LABEL"]
    LINES.append(r"\newcommand{\%s}{%s}%% %s [%s]" %
                 (name, fmt(r["VALUE"], r["ROUNDING_RULE"]), r["MANUSCRIPT_LABEL"], r["SOURCE_FILE"]))

# a few presentation aliases: absolute values and sign-stripped percentages
def alias(new, base, transform):
    row = next(x for x in REC["ROWS"] if x["MANUSCRIPT_LABEL"] == base)
    LINES.append(r"\newcommand{\%s}{%s}%% |%s|" %
                 (new, fmt(transform(row["VALUE"]), row["ROUNDING_RULE"]), base))

for nm, base in (("absFreshStaticDeviationPercent", "fresh_static_deviation_percent"),
                 ("absContinuumErrorStaticPercent", "continuum_error_static_percent"),
                 ("absContinuumErrorMobilePercent", "continuum_error_mobile_percent"),
                 ("absCellStaticMedianObservedPercent", "cell_static_median_observed_percent"),
                 ("absCellMobileMedianObservedPercent", "cell_mobile_median_observed_percent"),
                 ("absCellMobileMeanObservedPercent", "cell_mobile_mean_observed_percent"),
                 ("absCellStaticMedianSurrogatePercent", "cell_static_median_surrogate_percent"),
                 ("absCellMobileMedianSurrogatePercent", "cell_mobile_median_surrogate_percent"),
                 ("absCellMobileMedianConstructionPercent", "cell_mobile_median_construction_percent"),
                 ("absCellMobileMeanConstructionPercent", "cell_mobile_mean_construction_percent"),
                 ("absMSixSequentialStepZeroBaselineMTwoLevel", "m6_sequential_step_0_baseline_M2_level"),
                 ("absMSixSequentialStepOneAddSharedTrajectory", "m6_sequential_step_1_add_shared_trajectory"),
                 ("absMSixFactorialMainEffectSharedTrajectory", "main_effect_shared_trajectory_placeholder")):
    try:
        alias(nm, base, abs)
    except StopIteration:
        pass

LINES.append(r"\newcommand{\nReconciliationRows}{%d}%% count of reconciliation rows" % len(REC["ROWS"]))
seen["nReconciliationRows"] = "N_ROWS"

out = f"{PKG}/manuscript/numbers.tex"
open(out, "w", encoding="utf-8").write("\n".join(LINES) + "\n")
json.dump({m: seen[m] for m in sorted(seen)},
          open(f"{PKG}/provenance/PAPER_MACRO_INDEX.json", "w", encoding="utf-8"),
          indent=1, ensure_ascii=False)
print("macros emitted:", len(seen))
