"""V2 numerical/figure outputs. Historical scripts route here; originals in Git 0a872ac."""
import csv
import json
import numpy as np
from paths import ROOT, PKG, PROV, read, digest, dump

def reconcile():
    rows=[]
    def add(name,rel,path,units,level,decimals=3):
        value=read(rel)
        for key in path.split('/'):
            value=value[int(key)] if isinstance(value,list) else value[key]
        rows.append(dict(NAME=name,VALUE=value,UNITS=units,EVIDENCE_LEVEL=level,
            SOURCE_FILE=rel,SOURCE_SHA256=digest(ROOT/rel),JSON_PATH=path,DECIMALS=decimals))
    audit=(PROV/'AUDIT_RESULTS.json').relative_to(ROOT).as_posix();frz='OBFOR01/out/_freeze.json'
    for name,key in [('Lattice','L'),('Capacity','CAP'),('ReservoirTarget','S0'),('Feed','phi'),('Outflow','omega'),('Mortality','muX'),('Reaction','kX'),('Hop','p_hop'),('SeedX','X_SEED')]:
        add(name,frz,'FREEZE_MANIFEST/frozen_point/'+key,'model units','FROZEN_METHOD',9 if key=='p_hop' else 3)
    add('Margin',frz,'RESIDUAL_TOLERANCE/EQUIVALENCE_MARGIN_percent','percent','FROZEN_POINT_RULE',1)
    for name,nm in [('Static','static'),('Mobile','mobile'),('Ratio','ratio')]:
        for suffix,key,dec in [('Predicted','predicted',4),('Observed','observed',4),('Error','relative_error_percent',2),('MCSD','prediction_mc_sd_percent',3),('SE','se_percent',3)]:
            add(name+suffix,audit,f'endpoints/{nm}/{key}','lattice units or ratio' if suffix in ['Predicted','Observed'] else 'percent','RAW_RECOMPUTED',dec)
    for nm in ['static','mobile']:
        add(nm.title()+'TOST',audit,f'endpoints/{nm}/diagnostic_tost_p','p value','POST_FREEZE_DIAGNOSTIC',6)
    for name,key in [('Selected','A_mission_rule__nX_final_ge_40_and_ge_50_frames'),('NoPopulation','B_drop_the_population_threshold__keep_ge_50_frames'),('FiniteOnly','C_no_outcome_dependent_threshold_at_all')]:
        for suffix,k,unit in [('N','n','arms'),('Residual','percent','percent'),('SE','se_percent','percent')]:
            add(name+suffix,audit,f'historical_levels/{key}/{k}',unit,'OUTCOME_CONDITIONED_DEVELOPMENTAL')
    for name,key in [('BirthDifference','difference_pp'),('BirthSE','se_pp')]:
        add(name,audit,'replicates/'+key,'percentage points','POST_OUTCOME_DIAGNOSTIC')
    for name,key in [('Empirical','mobile_empirical'),('Poisson','mobile_poisson')]:
        add(name+'Mean',audit,f'replicates/stats/{key}/mean','percent','POST_OUTCOME_DIAGNOSTIC')
    repair='SEAL01/out/OBFOR01_SEAL_REPAIR_EVIDENCE.json'
    for name,path in [('NoSharedError','R4_DISCRIMINATING_POWER/WHAT_THE_TEST_DOES_REJECT/the model with the shared trajectory removed/relative_error_percent'),('IdealError','R4_DISCRIMINATING_POWER/WHAT_THE_TEST_DOES_REJECT/the uncorrected ideal operator/mobile/relative_error_percent')]:
        add(name,repair,path,'percent','POST_OUTCOME_MODEL_COMPARISON',2)
    for nm in ['static','mobile','ratio']:
        add('Baseline'+nm.title()+'Error',repair,f'R4_DISCRIMINATING_POWER/NULL_SCORED_ON_THE_THREE_FROZEN_ENDPOINTS/{nm}/relative_error_percent','percent','POST_OUTCOME_BASELINE_COMPARISON',2)
    add('HistoricalFluxArms',repair,'R3_HISTORICAL_ARMS_BEHIND_THE_BIRTH_FLUX','arms','FROZEN_INPUT_PROVENANCE',0)
    add('BlockedMean','OBFOR01/out/_adjudication.json','TECHNICAL/blocked_fraction_X_mean','fraction','RAW_RECOMPUTED',7)
    add('PQArchives','PQEC01/out/PQEC01_RAW_MANIFEST.json','N_ARCHIVES','archives','POST_OUTCOME_DEVELOPMENTAL',0)
    dump(PROV/'PAPER_NUMERICAL_RECONCILIATION.json',dict(version='V2',N_ROWS=len(rows),ROWS=rows,
        supersedes='Original 213 rows in Git 0a872ac; original rows are not current scientific claims.',
        source_manifest_sha256=digest(PROV/'SOURCE_MANIFEST.json')))
    with (PROV/'PAPER_NUMERICAL_RECONCILIATION.csv').open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
    print('V2 numerical rows:',len(rows))

def emit_numbers():
    rec=json.loads((PROV/'PAPER_NUMERICAL_RECONCILIATION.json').read_text())
    lines=['% Generated by code/emit_numbers.py; do not edit.']
    for r in rec['ROWS']:
        v=r['VALUE'];s=str(v) if isinstance(v,int) else f'{v:.{r["DECIMALS"]}f}'
        lines.append('\\newcommand{\\V'+r['NAME']+'}{'+s+'}% '+r['SOURCE_FILE']+' :: '+r['JSON_PATH'])
    (PKG/'manuscript/numbers.tex').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    dump(PROV/'PAPER_MACRO_INDEX.json',{'V'+r['NAME']:r['NAME'] for r in rec['ROWS']})

def figures():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    D=json.loads((PROV/'AUDIT_RESULTS.json').read_text());R=read('SEAL01/out/OBFOR01_SEAL_REPAIR_EVIDENCE.json')
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':9,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42,'svg.hashsalt':'ising-life-v2'})
    INK,BLUE,RED='#222831','#22658b','#a43a37';F=PKG/'figures';meta={}
    def save(fig,name,data):
        fig.savefig(F/(name+'.pdf'),bbox_inches='tight',metadata={'CreationDate':None,'ModDate':None,'Creator':'Ising Life V2 deterministic pipeline'})
        fig.savefig(F/(name+'.png'),bbox_inches='tight',dpi=180,metadata={'Software':'Ising Life V2'})
        plt.close(fig);dump(PKG/'figure_data'/(name+'.json'),data)
        meta[name]=dict(pdf_sha256=digest(F/(name+'.pdf')),png_sha256=digest(F/(name+'.png')),
            data_sha256=digest(PKG/'figure_data'/(name+'.json')),input_audit_sha256=digest(PROV/'AUDIT_RESULTS.json'))
    fig,ax=plt.subplots(figsize=(8,3.25));ax.set_axis_off()
    boxes=[(.02,.60,.26,.30,'Frozen lattice protocol\ntransport, reaction, decay\nreservoir exchange'),(.36,.60,.27,.30,'Historical birth-flux law\n40 engine arms\nmeasured input'),(.72,.60,.26,.30,'M6 predictor\nshared source trajectory\nsimulated before fresh arms'),(.36,.08,.27,.27,'Frozen point predictions\nstatic, mobile, ratio\nmargin: ±2.9%'),(.72,.08,.26,.27,'28 fresh engine arms\n14 static + 14 mobile\ncomparison only')]
    boxes[2]=(.72,.57,.26,.36,'M6 predictor\nshared source trajectory\nsimulated before\nfresh arms')
    for x,y,w,h,s in boxes:
        ax.add_patch(plt.Rectangle((x,y),w,h,facecolor='#eef3f6',edgecolor=BLUE,lw=1));ax.text(x+w/2,y+h/2,s,ha='center',va='center',fontsize=8.4)
    for a,b in [((.15,.95),(.84,.95)),((.63,.67),(.72,.67)),((.85,.57),(.50,.35)),((.63,.21),(.72,.21))]:
        ax.annotate('',xy=b,xytext=a,arrowprops=dict(arrowstyle='->',color=INK))
    ax.text(.02,.17,'No fresh outcome is supplied\nto the frozen predictor.\nThe measured input makes\nthe prediction conditional.',fontsize=9,va='center')
    save(fig,'fig1_model_and_event_order',{'kind':'information-flow schematic','sources':['OBFOR01/code/m6_obfor01.py','OBFOR01/out/_freeze.json','SEAL01/out/OBFOR01_PREDICTION_INFORMATION_FLOW.json']})
    fig,axs=plt.subplots(1,2,figsize=(8,3.5),gridspec_kw={'width_ratios':[1,1.15]})
    for i,(name,c) in enumerate([('static','S'),('mobile','M')]):
        e=D['endpoints'][name];v=[a['r80_median'] for a in D['fresh_arms'] if a['condition']==c]
        axs[0].scatter(np.linspace(i-.12,i+.12,len(v)),v,s=17,c=BLUE,zorder=3)
        axs[0].hlines(e['predicted'],i-.28,i+.28,color=RED,lw=2)
        axs[0].errorbar(i+.24,e['observed'],yerr=e['se_percent']/100*e['predicted'],fmt='D',ms=4,color=INK,capsize=3)
    axs[0].set(xticks=[0,1],xticklabels=['Static','Mobile'],ylabel='Within-arm median radius',title='A  Fresh arms (14 per condition)')
    axs[0].text(.02,.96,'Red: frozen prediction\nBlack: mean ± one SE',transform=axs[0].transAxes,va='top',fontsize=8)
    axs[1].axvspan(-2.9,2.9,color='#e9eef1');axs[1].axvline(0,color='0.5',lw=.6)
    for i,name in enumerate(['static','mobile','ratio']):
        axs[1].plot(D['endpoints'][name]['relative_error_percent'],i,'o',color=BLUE)
        axs[1].plot(R['R4_DISCRIMINATING_POWER']['NULL_SCORED_ON_THE_THREE_FROZEN_ENDPOINTS'][name]['relative_error_percent'],i+.14,'s',color=INK,ms=4)
    axs[1].set(yticks=[0,1,2],yticklabels=['Static','Mobile','Ratio'],xlabel='Observation / prediction − 1 (%)',title='B  Frozen point-rule comparison',xlim=(-3.4,3.4),ylim=(-.6,2.7))
    axs[1].text(.02,.98,'Blue: M6   Black: historical-copy baseline',transform=axs[1].transAxes,va='top',fontsize=7.5)
    fig.tight_layout();save(fig,'fig2_prospective_confirmation',{'fresh_arms':D['fresh_arms'],'endpoints':D['endpoints'],'historical_copy':R['R4_DISCRIMINATING_POWER']['NULL_SCORED_ON_THE_THREE_FROZEN_ENDPOINTS'],'error_bars':'one arm-level SE in panel A; panel B shows point rule only'})
    fig,ax=plt.subplots(figsize=(7.4,3.2));levels=list(D['historical_levels'].values())
    ax.errorbar([r['percent'] for r in levels],range(3),xerr=[r['se_percent'] for r in levels],fmt='o',color=BLUE,capsize=4);ax.axvline(0,color='0.5',ls='--',lw=.8)
    ax.set(yticks=range(3),yticklabels=[f'Terminal X ≥ 40; ≥ 50 frames (n={levels[0]["n"]})',f'No X threshold; ≥ 50 frames (n={levels[1]["n"]})',f'At least one finite radius (n={levels[2]["n"]})'],xlabel='Historical mobile residual (%)',title='Outcome-dependent inclusion changes the historical summary')
    ax.set_ylim(2.65,-.4);ax.text(.02,.03,'Bars: one SE across arms. All rows retain a final Y source.',transform=ax.transAxes,fontsize=8)
    fig.tight_layout();save(fig,'fig3_summary_rule_artefact',{'levels':D['historical_levels'],'note':'Developmental comparison; even the permissive row requires final Y >= 1 and a finite radius.'})
    fig,axs=plt.subplots(1,2,figsize=(8,3.5));adj=read('OBFOR01/out/_adjudication.json');obs=D['endpoints']['mobile']['observed']
    preds=adj['ABLATION']['predictions'];names=['full','poisson_births','no_shared_trajectory','ideal_population_value'];errs=[100*(obs/preds[n]-1) for n in names]
    axs[0].axvspan(-2.9,2.9,color='#e9eef1');axs[0].scatter(errs,range(4),color=[BLUE,BLUE,RED,RED])
    axs[0].set(yticks=range(4),yticklabels=['Frozen M6','Poisson source','No shared path','Ideal reference'],xlabel='Fresh mobile relative error (%)',title='A  Comparisons at the frozen margin',xlim=(-6,3.2));axs[0].invert_yaxis()
    for i,k in enumerate(['mobile_empirical','mobile_poisson']):
        vals=D['replicates']['values'][k];axs[1].scatter(np.linspace(i-.12,i+.12,16),vals,color=BLUE,s=15);axs[1].hlines(np.mean(vals),i-.22,i+.22,color=INK,lw=2)
    axs[1].set(xticks=[0,1],xticklabels=['Empirical flux','Poisson flux'],ylabel='Predictor residual (%)',title='B  Existing SEAL01 predictor replicas',ylim=(-6.15,-3.05))
    axs[1].text(.03,.97,'16 stored replicas × 30 arms per replica\nNo new simulations for V2',transform=axs[1].transAxes,va='top',fontsize=8)
    fig.tight_layout();save(fig,'fig4_mechanism_ablation',{'predictions':preds,'fresh_observed':obs,'errors_percent':dict(zip(names,errs)),'replicates':D['replicates'],'interpretation':'Poisson passes; greater distance is not a rejection. Earlier birth-flux magnitude/sign is not sustained.'})
    dump(PROV/'PAPER_FIGURE_PROVENANCE.json',meta);print('Four V2 figures regenerated.')

def tables():
    D=json.loads((PROV/'AUDIT_RESULTS.json').read_text())
    lines=[r'\begin{longtable}{llrrrr}',r'\toprule Condition & Seed & Median $r_{80}$ & Mean $r_{80}$ & Window $N_X$ & Blocked X \\',r'\midrule\endhead']
    for a in D['fresh_arms']:
        lines.append(f'{a["condition"]} & {a["seed"]} & {a["r80_median"]:.4f} & {a["r80_mean"]:.4f} & {a["N_X_window_mean"]:.2f} & {a["blocked_fraction"]:.7f} '+r'\\')
    lines += [r'\bottomrule\end{longtable}']
    (PKG/'supplement/S4_arms.tex').write_text('\n'.join(lines)+'\n')
