"""OMLDCT02 — the master freeze. Generated by committed code; every digest is recomputable.

Nothing in the scientific design moves. The law, the endpoints, the combination rule, the zero
treatment, the minimum pair count, the alpha, the direction and the resource ceiling are the ones
LDFMA01 handed over and the owner froze. What changed since OMLDCT01 is bookkeeping: fresh seeds, a
list long enough for the frozen accrual policy to complete, committed hash recipes, four distinct
digest labels, and a guard that refuses scientific scale before this file is committed.
"""
from __future__ import annotations
import json, os, sys, datetime, subprocess

REPO = os.environ.get("OMLDCT02_REPO", "/home/claude/edl")
sys.path.insert(0, os.path.join(REPO, "OMLDCT02", "code"))
import omldct02_hashes as H

OUT = f"{REPO}/OMLDCT02/out"
FREEZE = f"{OUT}/OMLDCT02_MASTER_FREEZE.json"
SIDECAR = f"{OUT}/OMLDCT02_MASTER_FREEZE.sha256.json"

TERMINAL_VOCABULARY = [
 "MATCHED_LOCKED_DAUGHTER_CONTROL_EFFECT_SUPPORTED",
 "MATCHED_LOCKED_DAUGHTER_CONTROL_EFFECT_NOT_DETECTED__INCONCLUSIVE_UNDER_FROZEN_POWER",
 "INSUFFICIENT_ADMISSIBLE_PAIRED_BLOCKS",
 "OMLDCT02_TECHNICALLY_INVALID"]

def git(*a): return subprocess.run(["git", "-C", REPO, *a], capture_output=True, text=True).stdout.strip()

def main():
    seeds = json.load(open(f"{OUT}/OMLDCT02_SEED_MANIFEST.json"))
    meth = json.load(open(f"{OUT}/OMLDCT02_METHODS_MANIFEST.json"))
    design = json.load(open(f"{OUT}/OMLDCT02_DESIGN_RECOMPUTED.json"))
    e3 = json.load(open(f"{OUT}/OMLDCT02_E3_QUALIFICATION.json"))
    st = json.load(open(f"{OUT}/OMLDCT02_FIVE_LINE_SELF_TEST.json"))
    forb = json.load(open(f"{OUT}/OMLDCT02_FORBIDDEN_SEEDS.json"))
    doc = {
     "MISSION": "OMLDCT02", "SECTION": "MASTER FREEZE",
     "GENERATED_UTC": datetime.datetime.now(datetime.timezone.utc).isoformat(),
     "THIS_FREEZE_PRECEDES_EVERY_SCIENTIFIC_WORLD": True,
     "TOKEN_REQUIRED_IN_THE_C2_COMMIT_MESSAGE": "OMLDCT02_C2_MASTER_FREEZE_COMMITTED",
     "INVALID_PREDECESSOR": "OMLDCT01 — ONE-MATCHED-LOCKED-DAUGHTER-CONTROL-TEST-01",
     "OMLDCT01_FINAL_DISPOSITION": "OMLDCT01_TECHNICALLY_INVALID",
     "OMLDCT01_INVALID_CLOSURE_TIP": seeds["OMLDCT01_INVALID_CLOSURE_TIP"],
     "SCIENTIFIC_PARENT": "LDFMA01 — LOCKED-DAUGHTER-FAILURE-MECHANISM-ARBITRATION-01",
     "SCIENTIFIC_PARENT_TIP": "2101b301a2444a4a825a6cd338a8db7334c53c9f",
     "PARENT_HANDOFF_SHA256": "e3ec4b929069a794b648feffc9b7b5d9315a7b96a74711fcd99746f931523029",

     "SELECTED_LAW": "LAW_C_MCTT01",
     "Y_LAW_BITS": seeds["LAW_BITS"],
     "NEW_PARAMETER_POINTS": 0, "X_LAWSPEC_BASELINE": "UNCHANGED",

     "PRIMARY_ENDPOINT": "paired post-intervention duration of the same locked daughter identity",
     "COPRIMARY_ENDPOINT": "paired post-intervention locked-daughter particle-step exposure",
     "SIGN_CONVENTION": "SELECTIVE minus SHAM, on the paired log difference",
     "PAIRED_TEST": "two-sided exact Wilcoxon signed-rank with Pratt ranking; the conditional "
                    "sign-flip distribution is enumerated by dynamic programming. No normal "
                    "approximation anywhere.",
     "ALPHA": 0.05,
     "PRIMARY_AND_COPRIMARY_COMBINATION": "AND_WITH_CONCORDANT_DIRECTION",
     "ZERO_DIFFERENCE_TREATMENT": "PRATT_EXACT_SIGN_FLIP",
     "MINIMUM_VALID_PAIR_COUNT": 41,
     "SUPPORT_REQUIRES": ["n_valid_pairs >= 41", "p_duration < 0.05", "p_exposure < 0.05",
                          "median_duration_difference != 0", "median_exposure_difference != 0",
                          "both median effects have the same sign"],
     "NULL_RESULT_INTERPRETATION": "INCONCLUSIVE__NO_CLAIM_OF_EQUIVALENCE__NO_CLAIM_OF_NO_EFFECT",
     "NO_EQUIVALENCE_MARGIN_EXISTS": True,
     "FORBIDDEN_WORDS_FOR_A_NON_POSITIVE_RESULT": ["NO_EFFECT", "EQUIVALENT", "UNCHANGED"],
     "TERMINAL_VOCABULARY": TERMINAL_VOCABULARY, "NO_FIFTH_DISPOSITION": True,

     "MATCHED_DESIGN": {
       "unit": "the base block — one seed, one trigger, both arms",
       "arms": ["SELECTIVE_PARENT_REMOVAL", "SHAM_NO_REMOVAL"],
       "time_origin": "t_m, the frozen trigger step, identical in both arms by construction",
       "procedure": ["one common prefix to the frozen functional-maturity time t_m",
                     "lock the uniquely reconstructed daughter",
                     "record complete physical and RNG state",
                     "fork two bit-identical continuations"],
       "the_originally_locked_daughter_is_followed": True,
       "forbidden": ["later daughter replacement", "identity restart", "later interval substitution",
                     "ambient-population identity substitution"],
       "identity_terminates_at": ["split", "merge", "tie or ambiguity", "empty component",
                                  "administrative horizon"],
       "one_base_seed_contributes_at_most_one_valid_paired_observation": True},

     "ACCRUAL_RULE": "process the frozen base seeds in index order until 41 technically valid "
                     "admissible pairs are retained, or the hard 512-arm-instance ceiling is "
                     "exhausted. A base seed without an admissible trigger consumes its predeclared "
                     "cost and is never selectively replaced. A technical retry uses the identical "
                     "seed and arm. A scientific non-trigger consumes its seed.",
     "TARGET_VALID_PAIRED_BLOCKS": 41,
     "MAX_PRIMARY_ARM_INSTANCES": 512,
     "ONE_ARM_INSTANCE": "one full-horizon world-equivalent of engine work, T = 11000 steps",
     "PREFIX_TRUNCATION": "the common prefix runs only to the frozen LATEST_ALLOWED_TRIGGER = 6500, "
                          "because a maturation candidate after that step fails the frozen deadline "
                          "gate. This uses the frozen rule and changes no definition.",
     "MAX_UNEXTERNALISED_ARM_INSTANCES": 16,
     "MAX_TECHNICAL_RESERVES": 6,
     "MAX_INTENTIONAL_COMMITS": 5, "MAX_INDEPENDENT_CHECKERS": 1,
     "REVIEW_CASCADE": "forbidden", "MAX_POST_OUTCOME_SCIENTIFIC_REPAIRS": 0,
     "SECOND_CLEAN_RESTART": "forbidden",

     "SEED_SET_HASH": seeds["SEED_SET_HASH"], "N_BASE_SEEDS": seeds["N_BASE"],
     "N_RESERVE_SEEDS": seeds["N_RESERVE"],
     "SEED_DERIVATION": seeds["DERIVATION"],
     "FORBIDDEN_SET_HASH": forb["FORBIDDEN_SET_HASH"], "FORBIDDEN_SET_SIZE": forb["SIZE"],
     "SEED_DISJOINTNESS": seeds["DISJOINTNESS"],

     "METHODS_HASH": meth["METHODS_HASH"], "N_METHODS_FILES": meth["N_FILES"],
     "METHODS_CLOSURE_AGREEMENT": meth["TWO_INDEPENDENT_CLOSURES"]["EXACT_AGREEMENT"],
     "METHODS_CLOSURE_NOTE": meth["TWO_INDEPENDENT_CLOSURES"]["WHAT_IS_BOUND"],
     "SCIPY": meth["SCIPY"],

     "DESIGN_CONTENT_HASH": design["DESIGN_CONTENT_HASH"],
     "PRE_RUN_DISCLOSURES": {
       "P_reaching_41_pairs": design["RECOMPUTED_AT_THE_1024_SEED_LIST"]["P_reaching_target"],
       "P_under_accrual": design["RECOMPUTED_AT_THE_1024_SEED_LIST"]["P_under_accrual"],
       "what_OMLDCT01_disclosed": design["WHAT_OMLDCT01_DISCLOSED"],
       "the_finding": design["THE_FINDING"]["what"],
       "these_are_disclosures_not_gates": True},

     "PRE_RUN_E3_QUALIFICATION": e3["PRE_RUN_E3_QUALIFICATION"],
     "E3_QUALIFICATION_CONTENT_HASH": e3["QUALIFICATION_CONTENT_HASH"],
     "FIVE_LINE_DECISION_SELF_TEST": st.get("FIVE_LINE_DECISION_SELF_TEST", st.get("VERDICT")),

     "PRE_C2_SCIENTIFIC_SCALE_GUARD": {
       "module": "OMLDCT02/code/omldct02_guard.py",
       "rule": "L > 5, or horizon >= NEED = 250, or a seed in this manifest, makes a construction "
               "scientific-scale and requires a committed C2",
       "it_reads_git_not_the_working_tree": True,
       "PRE_C2_SCIENTIFIC_SCALE_EXECUTIONS": 0},

     "CLAIM_CEILING": "a positive result establishes at most that, under one frozen law, selective "
                      "removal of the parent changed both the post-removal identity duration and "
                      "the particle-step exposure of the same locked daughter relative to a "
                      "bit-identical sham, with concordant effect direction.",
     "IT_DOES_NOT_ESTABLISH": ["constituent turnover", "minimal reproduction",
                               "strong self-reproduction", "heredity", "multigeneration",
                               "living status", "architecture necessity"],
     "H3_STATUS": "NOT_TESTED", "REPRODUCTION_STATUS": "NOT_TESTED", "HEREDITY_STATUS": "NOT_TESTED",
     "AUTONOMOUS_COHESION_STATUS": "NOT_ESTABLISHED",
     "ARCHITECTURE_CHANGE_NECESSITY": "NOT_ESTABLISHED",
     "COMPANION_PAPER_V1_1_STATUS": "UNPUBLISHED__NOT_SUBMITTED__PUBLICATION_DEFERRED",

     "HASH_LABELS": H.FOUR_DISTINCT_LABELS,
     "CANONICAL_RULES": H.CANONICAL_RULES,
     "HASH_RECIPES_COMMITTED": True,
     "WORLDS_RUN_AT_FREEZE_TIME": 0,
    }
    doc["FREEZE_CONTENT_HASH"] = H.content_digest(doc)
    with open(FREEZE, "w") as fh: json.dump(doc, fh, indent=1)
    side = {"MISSION": "OMLDCT02", "SECTION": "master freeze file digest",
            "WHY_A_SIDECAR": "a file cannot contain its own file digest. OMLDCT01 stored the file "
                             "digest inside a record under the key FREEZE_HASH, which the master "
                             "freeze used for a digest of its own content — one label over two "
                             "quantities. The two are named separately here and kept apart.",
            "FREEZE_FILE": "OMLDCT02_MASTER_FREEZE.json",
            "FREEZE_FILE_SHA256": H.file_sha256(FREEZE),
            "FREEZE_CONTENT_HASH": doc["FREEZE_CONTENT_HASH"],
            "FREEZE_CONTENT_HASH_RULE": "H.content_digest: canonical digest of the document with "
                                        "its own digest fields and GENERATED_UTC removed"}
    with open(SIDECAR, "w") as fh: json.dump(side, fh, indent=1)
    print("FREEZE_CONTENT_HASH =", doc["FREEZE_CONTENT_HASH"])
    print("FREEZE_FILE_SHA256  =", side["FREEZE_FILE_SHA256"])
    print("METHODS_HASH        =", doc["METHODS_HASH"])
    print("SEED_SET_HASH       =", doc["SEED_SET_HASH"])

if __name__ == "__main__":
    main()
