"""OMLDCT02 — the fresh seed registry, generated by committed code from a declared derivation.

OMLDCT01's seed list is not authoritative here for two independent reasons: its SEED_SET_HASH could
not be recomputed from the repository, and four of its seeds were retired AFTER their outcomes were
known, which makes the surviving list outcome-informed. OMLDCT02 does not remove indices 0-3 from
that list. It generates an entirely new ordered list and proves it disjoint from everything the
programme has ever run.
"""
from __future__ import annotations
import json, hashlib, os, sys, datetime

REPO = os.environ.get("OMLDCT02_REPO", "/home/claude/edl")
sys.path.insert(0, os.path.join(REPO, "OMLDCT02", "code"))
import omldct02_hashes as H

# --------------------------------------------------------------------------- frozen inputs
OMLDCT01_INVALID_CLOSURE_TIP = "d8b5007744ce14ea056d8cdab8e4fd520086ba53"
MISSION = "OMLDCT02"
LAW_NAME = "LAW_C_MCTT01"
LAW_BITS = {"kY": "0x3f50763f01e8e5b2", "muY": "0x3f484713dc1c8ab5",
            "p_hop_Y": "0x3fba462ec93926a0"}
LAW_STRING = f'{LAW_NAME}|kY={LAW_BITS["kY"]}|muY={LAW_BITS["muY"]}|p_hop_Y={LAW_BITS["p_hop_Y"]}'

N_BASE = 1024      # recomputed below, not inherited
N_RESERVE = 6      # MAX_TECHNICAL_RESERVES in the committed parent handoff
SEED_SPACE = 1 << 32

DERIVATION = ("seed(role, index, nonce) = the first 4 bytes, big-endian, of "
              "sha256('<OMLDCT01 invalid-closure tip>|OMLDCT02|<law string>|<role>|<index>' and, "
              "only when a nonce is needed, '|<nonce>'), interpreted as an unsigned 32-bit "
              "integer. nonce starts at 0 and increments only when the candidate collides with an "
              "already-accepted OMLDCT02 seed or with the forbidden set. Every nonce actually used "
              "is recorded, so the whole list is recomputable from this file alone.")

def derive(role, index, nonce=0):
    m = f"{OMLDCT01_INVALID_CLOSURE_TIP}|{MISSION}|{LAW_STRING}|{role}|{index}"
    if nonce: m += f"|{nonce}"
    return int.from_bytes(hashlib.sha256(m.encode("utf-8")).digest()[:4], "big"), m

# --------------------------------------------------------------------------- the forbidden set
def load_forbidden():
    """Read the FROZEN forbidden set. It is NOT re-harvested here.

    The first version of this generator harvested it live, and was not reproducible: once it had
    written its own manifest, that file sat in the repository with OMLDCT02's seeds under keys
    containing 'seed', so the next run forbade its own output and produced a different list. Caught
    before C1 and fixed structurally — the harvest is its own committed idempotent step in
    omldct02_forbidden_seeds.py and this generator only consumes its frozen result."""
    p = f"{REPO}/OMLDCT02/out/OMLDCT02_FORBIDDEN_SEEDS.json"
    doc = json.load(open(p))
    got = H.canonical_digest(doc["FORBIDDEN_SEEDS"])
    if got != doc["FORBIDDEN_SET_HASH"]:
        raise SystemExit(f"forbidden set digest mismatch: {got} != {doc['FORBIDDEN_SET_HASH']}")
    return set(doc["FORBIDDEN_SEEDS"]), doc

# --------------------------------------------------------------------------- generation
def generate(forbidden):
    seeds = []; used = set(); max_nonce = 0; collisions = []
    for role, n in (("BASE", N_BASE), ("RESERVE", N_RESERVE)):
        for i in range(n):
            nonce = 0
            while True:
                s, material = derive(role, i, nonce)
                if s not in forbidden and s not in used: break
                collisions.append({"role": role, "index": i, "nonce": nonce, "rejected_seed": s,
                                   "why": "in the forbidden set" if s in forbidden else
                                          "already taken by an earlier OMLDCT02 index"})
                nonce += 1
            used.add(s); max_nonce = max(max_nonce, nonce)
            seeds.append({"role": role, "index": i, "seed": s, "nonce": nonce})
    return seeds, max_nonce, collisions

def main():
    forbidden, fdoc = load_forbidden()
    src, n_json = fdoc["COUNT_BY_SOURCE"], fdoc["JSON_FILES_SCANNED"]
    seeds, max_nonce, collisions = generate(forbidden)
    base = [s for s in seeds if s["role"] == "BASE"]
    res = [s for s in seeds if s["role"] == "RESERVE"]
    bset = {s["seed"] for s in base}; rset = {s["seed"] for s in res}
    old = json.load(open(f"{REPO}/OMLDCT01/out/OMLDCT01_SEED_MANIFEST.json"))
    old_seeds = {d["seed"] for d in old["BASE_SEEDS"]} | {d["seed"] for d in old["RESERVE_SEEDS"]}
    pilots = {1440724471, 818998374, 3087639930, 2434593729}
    doc = {
     "MISSION": "OMLDCT02", "SECTION": "seed registry",
     "GENERATED_UTC": datetime.datetime.now(datetime.timezone.utc).isoformat(),
     "GENERATOR": "OMLDCT02/code/omldct02_seed_manifest.py — committed, and this list is fully "
                  "recomputable from it plus the recorded nonces",
     "OMLDCT01_INVALID_CLOSURE_TIP": OMLDCT01_INVALID_CLOSURE_TIP,
     "LAW_STRING": LAW_STRING, "LAW_BITS": LAW_BITS,
     "DERIVATION": DERIVATION,
     "MAX_NONCE_USED": max_nonce, "N_COLLISION_REJECTIONS": len(collisions),
     "COLLISION_REJECTIONS": collisions[:50],
     "N_BASE": len(base), "N_RESERVE": len(res),
     "WHY_N_BASE_IS_NOT_474": "OMLDCT01 froze 474 base seeds and disclosed P(reaching 41 pairs) = "
       "0.5063. The recomputation in OMLDCT02_DESIGN_RECOMPUTED.json shows that probability was "
       "governed by the LENGTH OF THE SEED LIST, not by the 512-instance ceiling: with the ceiling "
       "alone the probability is 1.0000 and the largest number of seeds ever consumed in 20000 "
       "simulated campaigns was 788. A 474-long list stops the campaign before the frozen ceiling "
       "does. OMLDCT02 freezes 1024 so that the frozen ceiling is what binds. No frozen design "
       "quantity moves: the target is still 41 pairs and the ceiling is still 512 arm instances.",
     "FORBIDDEN_SET": {
       "size": len(forbidden), "sources": src, "json_files_scanned": n_json,
       "frozen_artefact": "OMLDCT02_FORBIDDEN_SEEDS.json",
       "FORBIDDEN_SET_HASH": fdoc["FORBIDDEN_SET_HASH"],
       "verified_on_load": True,
       "rule": fdoc["RULE"]},
     "DISJOINTNESS": {
       "from_OMLDCT01_all_seeds": len(bset & old_seeds) == 0 and len(rset & old_seeds) == 0,
       "n_OMLDCT01_seeds_checked": len(old_seeds),
       "from_the_four_pre_C2_pilot_seeds": len((bset | rset) & pilots) == 0,
       "from_every_harvested_source": len((bset | rset) & forbidden) == 0,
       "base_internally_distinct": len(bset) == len(base),
       "reserve_internally_distinct": len(rset) == len(res),
       "base_and_reserve_disjoint": len(bset & rset) == 0},
     "ACCRUAL_ORDER": "BASE index 0 upward. A base seed without an admissible trigger consumes its "
                      "cost and is never selectively replaced. A technical retry reuses the "
                      "identical seed and arm. Reserves are technical only.",
     "BASE_SEEDS": base, "RESERVE_SEEDS": res,
    }
    doc["SEED_SET_HASH"] = H.seed_set_hash(seeds)
    doc["SEED_SET_HASH_RULE"] = ("H.seed_set_hash: canonical digest of [[role, index, seed], ...] "
                                 "in frozen order. Rules in omldct02_hashes.CANONICAL_RULES.")
    doc["DISJOINTNESS"]["ALL_PASS"] = all(v for v in doc["DISJOINTNESS"].values() if isinstance(v, bool))
    json.dump(doc, open(f"{REPO}/OMLDCT02/out/OMLDCT02_SEED_MANIFEST.json", "w"), indent=1)
    print("forbidden set:", len(forbidden), "from", src, f"({n_json} json files scanned)")
    print("N_BASE =", len(base), " N_RESERVE =", len(res), " max nonce =", max_nonce,
          " rejections =", len(collisions))
    print("DISJOINTNESS ALL_PASS =", doc["DISJOINTNESS"]["ALL_PASS"])
    print("SEED_SET_HASH =", doc["SEED_SET_HASH"])

if __name__ == "__main__":
    main()
