"""OMLDCT02 — the methods manifest, generated by committed code.

Two independent closures are computed and BOTH are reported: a runtime import trace of the declared
entry points, and a static AST traversal of the same entry points. OMLDCT01 found these disagreed
(21 files against 24) and bound the union; the disagreement is reported here rather than resolved by
trimming, because a superset closure can only over-bind and can never leave an executing file
unhashed.
"""
from __future__ import annotations
import json, os, sys, ast, datetime, importlib, subprocess

REPO = os.environ.get("OMLDCT02_REPO", "/home/claude/edl")
sys.path.insert(0, os.path.join(REPO, "OMLDCT02", "code"))
import omldct02_hashes as H

ENTRY_POINTS = ["OMLDCT02/code/omldct02_fork.py",
                "OMLDCT02/code/omldct02_analysis.py",
                "OMLDCT02/code/omldct02_e3_a.py",
                "OMLDCT02/code/omldct02_e3_b.py",
                "OMLDCT02/code/omldct02_guard.py",
                "OMLDCT02/code/omldct02_hashes.py",
                "OMLDCT02/code/omldct02_seed_manifest.py",
                "OMLDCT02/code/omldct02_forbidden_seeds.py",
                "OMLDCT02/code/omldct02_design.py",
                "OMLDCT02/code/omldct02_e3_bind.py",
                "OMLDCT02/code/omldct02_e3_qualify.py",
                "OMLDCT02/code/omldct02_selftest.py",
                "OMLDCT02/code/omldct02_methods_manifest.py",
                "OMLDCT02/code/omldct02_freeze.py",
                "OMLDCT02/code/omldct02_run.py",
                "OMLDCT02/code/omldct02_verify_freeze.py"]

SEARCH_DIRS = None   # filled at run time from the repository layout

def _code_dirs():
    out = []
    for d in sorted(os.listdir(REPO)):
        p = os.path.join(REPO, d, "code")
        if os.path.isdir(p): out.append(p)
    out.append(os.path.join(REPO, "LDFMA01", "code"))
    return sorted(set(out))

def _resolve(name, dirs):
    for d in dirs:
        p = os.path.join(d, name + ".py")
        if os.path.exists(p): return p
    return None

def ast_closure():
    """static: follow every plain module import name that resolves inside the repository."""
    dirs = _code_dirs(); seen = set(); stack = [os.path.join(REPO, e) for e in ENTRY_POINTS]
    unresolved = set()
    while stack:
        p = stack.pop()
        rp = os.path.realpath(p)
        if rp in seen or not os.path.exists(rp): continue
        seen.add(rp)
        try: tree = ast.parse(open(rp).read())
        except Exception: continue
        names = set()
        for n in ast.walk(tree):
            if isinstance(n, ast.Import):
                for a in n.names: names.add(a.name.split(".")[0])
            elif isinstance(n, ast.ImportFrom):
                if n.module and n.level == 0: names.add(n.module.split(".")[0])
        for nm in names:
            q = _resolve(nm, dirs)
            if q: stack.append(q)
            elif nm not in ("numpy", "json", "os", "sys", "math", "hashlib", "datetime", "copy",
                            "time", "re", "ast", "io", "tokenize", "subprocess", "importlib",
                            "collections", "itertools", "struct", "glob", "csv", "statistics",
                            "traceback", "__future__", "functools", "random", "typing", "pathlib"):
                unresolved.add(nm)
    return seen, sorted(unresolved)

def runtime_closure():
    """dynamic: import every entry point in a subprocess and report the repository files that ended
    up in sys.modules."""
    script = (
      "import sys,os,json\n"
      f"REPO={REPO!r}\n"
      "os.environ['OMLDCT02_REPO']=REPO; os.environ['LDFMA01_REPO']=REPO\n"
      "sys.path.insert(0,os.path.join(REPO,'OMLDCT02','code'))\n"
      "sys.path.insert(0,os.path.join(REPO,'TLMR01','code'))\n"
      "sys.path.insert(0,os.path.join(REPO,'LDFMA01','code'))\n"
      "eps=" + json.dumps([os.path.basename(e)[:-3] for e in ENTRY_POINTS]) + "\n"
      "import importlib\n"
      "for m in eps:\n"
      "    try: importlib.import_module(m)\n"
      "    except Exception: pass\n"
      "out=[]\n"
      "for m in list(sys.modules.values()):\n"
      "    f=getattr(m,'__file__',None)\n"
      "    if f and os.path.realpath(f).startswith(os.path.realpath(REPO)): out.append(os.path.realpath(f))\n"
      "print(json.dumps(sorted(set(out))))\n")
    r = subprocess.run([sys.executable, "-c", script], capture_output=True, text=True, cwd=REPO)
    try: return set(json.loads(r.stdout.strip().splitlines()[-1])), r.returncode == 0
    except Exception: return set(), False

def main():
    A, unresolved = ast_closure()
    R, rt_ok = runtime_closure()
    union = sorted(A | R)
    rel = lambda p: "/" + os.path.relpath(p, REPO).replace(os.sep, "/")
    modules = [{"path": rel(p), "sha256": H.file_sha256(p)} for p in union]
    modules.sort(key=lambda m: m["path"].encode("utf-8"))
    doc = {
     "MISSION": "OMLDCT02", "SECTION": "methods manifest",
     "GENERATED_UTC": datetime.datetime.now(datetime.timezone.utc).isoformat(),
     "GENERATOR": "OMLDCT02/code/omldct02_methods_manifest.py — committed",
     "PYTHON": sys.version.split()[0],
     "SCIPY": {
       "IS_SCIPY_IMPORTED_INTO_THE_PROCESS": True,
       "BY_WHICH_FILE": "/FMRT01/code/fmrt01_endpoint.py, at module level: 'from scipy.stats import binom'",
       "IMPORT_CHAIN": "omldct02_fork -> tlmr01_world -> fmrt01_endpoint -> scipy.stats",
       "WHY_IT_IS_THERE": "the frozen engine tlmr01_world imports fmrt01_endpoint for state_of, "
                          "local_x_masses and f5_ratio. None of those three uses scipy.",
       "THE_ONLY_SCIPY_CALL_IN_THAT_FILE": "binom.ppf inside survivor_upper(), which is on no "
                                           "OMLDCT02 path and is never called by this mission.",
       "DOES_ANY_OMLDCT02_ENDPOINT_GATE_OR_TEST_USE_SCIPY": False,
       "THE_EXACT_TEST": "the conditional sign-flip distribution is enumerated by dynamic "
                         "programming; omldct02_analysis imports fractions and numpy, and importing "
                         "it alone does not pull scipy into the process.",
       "A_CORRECTION": "OMLDCT01's methods closure recorded 'scipy: not imported anywhere'. That was "
                       "false as stated — scipy has been in the process since the engine was "
                       "written. Corrected here rather than repeated, and a runtime sentinel in the "
                       "batch runner records whether binom.ppf is ever actually called."},
     "ENTRY_POINTS": ENTRY_POINTS,
     "TWO_INDEPENDENT_CLOSURES": {
       "ast_traversal_n": len(A), "runtime_import_trace_n": len(R),
       "runtime_trace_succeeded": rt_ok,
       "EXACT_AGREEMENT": sorted(A) == sorted(R),
       "only_in_ast": sorted(rel(p) for p in (A - R)),
       "only_in_runtime": sorted(rel(p) for p in (R - A)),
       "unresolved_import_names": unresolved,
       "WHAT_IS_BOUND": "the UNION. A superset closure can only over-bind and can never leave an "
                        "executing file unhashed. The disagreement is reported, not trimmed away."},
     "N_FILES": len(modules), "MODULES": modules,
     "METHODS_HASH": H.methods_hash(modules),
     "METHODS_HASH_RULE": "H.methods_hash: canonical digest of [[path, sha256], ...] ordered "
                          "byte-lexicographically by path. Rules in omldct02_hashes.CANONICAL_RULES.",
    }
    json.dump(doc, open(f"{REPO}/OMLDCT02/out/OMLDCT02_METHODS_MANIFEST.json", "w"), indent=1)
    print(f"ast {len(A)}  runtime {len(R)}  union {len(modules)}  agree {sorted(A)==sorted(R)}")
    if A - R: print("  only in ast:", sorted(rel(p) for p in (A - R))[:6])
    if R - A: print("  only in runtime:", sorted(rel(p) for p in (R - A))[:6])
    print("unresolved import names:", unresolved)
    print("METHODS_HASH =", doc["METHODS_HASH"])

if __name__ == "__main__":
    main()
